// This file is automatically generated. Do not edit it directly.
// NOTE: This project uses MySQL, not Supabase. This file is kept for compatibility
// but will return a mock client that doesn't actually connect to Supabase.

import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use placeholder values to prevent "supabaseUrl is required" error
// TODO: Replace all Supabase imports with MySQL API calls throughout the codebase
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a client with placeholder values to prevent initialization errors
// This client won't work for actual operations but will prevent crashes
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});